### PR TITLE
Added fmt script

### PR DESCRIPTION
**Pull request by filiplazovic**

### CODE REVIEW

**Comment by drewstone** [comment]
Is this the same formatting as Parity/Substrate?

**Comment by filiplazovic** [comment]
No, we had our own fmt config: https://github.com/webb-tools/protocol-substrate/blob/main/rustfmt.toml
But I found that this is what substrate uses: https://github.com/paritytech/substrate/blob/master/rustfmt.toml
I can update that

**Comment by filiplazovic** [comment]
Using the config from substrate repo

**Comment by drewstone** [comment]
@filiplazovic can you add this same fmt script to the `dkg-substrate` node too.

**Pull request merged**
