### PR TITLE
chore: fix cargo docs from failing

### LINKED ISSUE #225: [Issue] Fix Doc CI
**Issue summary**

Fix Doc CI

**Other information and links**

### PR DESCRIPTION
**Pull request by dutterbutter**
**Summary of changes**

Changes introduced in this pull request:
- Adds submodules deps 

**Reference issue to close (if applicable)**

Closes #225

### CODE REVIEW

**Comment by dutterbutter** [comment]
Still an issue building docs in the CI for some reason. It could be due to this reported issue that seems to have regressed https://github.com/rust-lang/rust/issues/93476, but reportedly should be fixed in https://github.com/rust-lang/rust/pull/96447

**Error:**
```
error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `webb-client`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name webb_client client/src/lib.rs -o /home/runner/work/protocol-substrate/protocol-substrate/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=668ea3d87c858775 -L dependency=/home/runner/work/protocol-substrate/protocol-substrate/target/debug/deps --extern async_std=/home/runner/work/protocol-substrate/protocol-substrate/target/debug/deps/libasync_std-ed4ce62ea06324cd.rmeta --extern codec=/home/runner/work/protocol-substrate/protocol-substrate/target/debug/deps/libparity_scale_codec-0a1d53ccd132db98.rmeta --extern subxt=/home/runner/work/protocol-substrate/protocol-substrate/target/debug/deps/libsubxt-35710cea342ecd9b.rmeta --crate-version 0.1.0` (exit status: 1)
```

**Backtrace**
<details>
```
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:930:16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/panicking.rs:135:14
   2: core::panicking::panic_display
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/panicking.rs:65:5
   3: core::panicking::panic_str
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/option.rs:1840:5
   5: rustdoc::passes::collect_intra_doc_links::resolve_associated_trait_item
   6: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
   7: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve
   8: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_link
   9: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  10: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
  11: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
  13: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  14: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  15: <rustc_session::session::Session>::time::<rustdoc::clean::types::Crate, rustdoc::core::run_global_ctxt::{closure#8}>
  16: rustdoc::core::run_global_ctxt
  17: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#0}>
  18: <rustc_interface::interface::Compiler>::enter::<rustdoc::main_options::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  19: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustdoc::main_options::{closure#0}>::{closure#1}>
  20: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustdoc::main_options::{closure#0}>
  21: rustdoc::main_options
  22: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustdoc::main_args::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by drewstone** [comment]
@dutterbutter what is the status of this?

**Comment by dutterbutter** [comment]
@drewstone I cannot seem to determine why `cargo doc` is failing in the CI with `error: could not document `webb-client` as described above.

Running the commands locally works perfectly fine and you can view the docs accordingly. However in the CI it is not the case. I will try to playing with different rust versions perhaps but we are not seeing this issue on any of other Rust doc workflows.

**Comment by drewstone** [comment]
Can we exclude the client from the docs and get this working again @dutterbutter ?

**Comment by dutterbutter** [comment]
Yes that shouldn't be a problem.

**Comment by dutterbutter** [comment]
Closing in favour of #225

**Pull request closed without merging**
